{"name": "test_login_with_invalid_credentials[\\u9519\\u8bef\\u9a8c\\u8bc1\\u7801-123456-400]", "status": "passed", "description": "账号登录验证", "steps": [{"name": "登录手机号", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\86176\\PycharmProjects\\PythonProject1\\tests\\auth\\test_auth.py\", line 23, in test_login_with_invalid_credentials\n    code = input(\"请输入19054134384的验证码:\").strip()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1751446717763, "stop": 1751446724947}], "parameters": [{"name": "case_name", "value": "'错误验证码'"}, {"name": "code", "value": "'123456'"}, {"name": "expected_status", "value": "400"}], "start": 1751446717763, "stop": 1751446724947, "uuid": "901541db-3ca9-45d2-95f2-733f17c3b218", "testCaseId": "f06d456ef5c4817515b1738460217c17", "fullName": "tests.auth.test_auth#test_login_with_invalid_credentials"}